[package]
name = "protobuf-gen-rust"
version = "0.1.0"
authors = ["Li, Shulong <shulong.li.buaa@gmail.com>>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
bytes = "0.5.3"
protoc-rust = "2.10.1"
